namespace SLText.Core.Engine.Model;

/// <summary>A git commit with its metadata.</summary>
public class CommitInfo
{
    /// <summary>Full 40-char SHA-1 hash.</summary>
    public string Sha { get; init; } = "";

    /// <summary>Short (7-char) SHA for display.</summary>
    public string ShortSha => Sha.Length >= 7 ? Sha[..7] : Sha;

    /// <summary>The commit message subject line.</summary>
    public string Message { get; init; } = "";

    /// <summary>Fully commit message including body.</summary>
    public string FullMessage { get; init; } = "";

    /// <summary>Name of the author/committer.</summary>
    public string AuthorName { get; init; } = "";

    /// <summary>Email of the author.</summary>
    public string AuthorEmail { get; init; } = "";

    /// <summary>When the commit was created.</summary>
    public DateTime CommittedAt { get; init; }

    /// <summary>Tree object ID (hex, usually 40 chars).</summary>
    public string? TreeId { get; init; }

    /// <summary>List of parent SHAs.</summary>
    public List<string> ParentShas { get; init; } = new();

    /// <summary>All changed file paths in this commit.</summary>
    public List<string> ChangedFiles { get; init; } = new();

    /// <summary>HUMAN-READABLE relative time string ("2 days ago"). Generated by the View layer.</summary>
    public string RelativeTime => CommittedAt.Kind == DateTimeKind.Utc
        ? $"{DateTimeOffset.UtcNow.Subtract(CommittedAt.ToLocalTime())}"
        : $"{DateTime.Now.Subtract(CommittedAt)}";
}
